import "@/styles/globals.css";

import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import Providers from "./_components/providers";
import Header from "./_components/header";
import Player from "./_components/player/player";
import { Toaster } from "@/components/ui/sonner";
import { getServerAuthSession } from "@/server/auth";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerAuthSession();
  const content = session ? (
    <>
      {children}
      <Player />
    </>
  ) : (
    "Veuillez vous connecter"
  );
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        <Providers>
          <Header />
          {content}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
